### ISSUE TITLE
Adding support for code actions?

### ISSUE THREAD

**Issue by yatesco** [jiz4oh/vim-lspfuzzy#1]
Hi - thanks for this! Do you have any plans to add support for code actions?

**Comment by jiz4oh** [comment]
Hi, I'm not familiar with code action since none of the language servers I'm currently using support it, so I have no plans to add it for the time being, but welcome to pr

**Comment by jiz4oh** [comment]
Hi @yatesco, the support for code actions is added now, welcome any feedbacks
